### ISSUE TITLE
Error: spawnSync docker ENOENT

### ISSUE THREAD

**Issue by omar16100** [aws-samples/aws-codecommit-devops-model#3]
I wanted try this example and ran into the following error

The error occurs at this command :

```bash
npm run init
```
More detailed :

```bash
Failed to build file at /home/omar/aws-codecommit-devops-model/assets/pr-build-events/handler.ts: Error: spawnSync docker ENOENT
Subprocess exited with error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-codecommit-devops-model@1.0.0 init: `npm i --prefix assets/approval-rule-template && npm i --prefix assets/pr-build-events && npm i && ./node_modules/aws-cdk/bin/cdk bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-codecommit-devops-model@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/omar/.npm/_logs/2020-06-02T11_07_27_538Z-debug.log
```

From /home/omar/.npm/_logs/2020-06-02T11_07_27_538Z-debug.log

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'init' ]
2 info using npm@6.14.5
3 info using node@v14.3.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle aws-codecommit-devops-model@1.0.0~preinit: aws-codecommit-devops-model@1.0.0
6 info lifecycle aws-codecommit-devops-model@1.0.0~init: aws-codecommit-devops-model@1.0.0
7 verbose lifecycle aws-codecommit-devops-model@1.0.0~init: unsafe-perm in lifecycle true
8 verbose lifecycle aws-codecommit-devops-model@1.0.0~init: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/omar/aws-codecommit-devops-model/node_modules/.bin:/home/omar/bin:/home/omar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle aws-codecommit-devops-model@1.0.0~init: CWD: /home/omar/aws-codecommit-devops-model
10 silly lifecycle aws-codecommit-devops-model@1.0.0~init: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm i --prefix assets/approval-rule-template && npm i --prefix assets/pr-build-events && npm i && ./node_modules/aws-cdk/bin/cdk bootstrap'
10 silly lifecycle ]
11 silly lifecycle aws-codecommit-devops-model@1.0.0~init: Returned: code: 1  signal: null
12 info lifecycle aws-codecommit-devops-model@1.0.0~init: Failed to exec init script
13 verbose stack Error: aws-codecommit-devops-model@1.0.0 init: `npm i --prefix assets/approval-rule-template && npm i --prefix assets/pr-build-events && npm i && ./node_modules/aws-cdk/bin/cdk bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid aws-codecommit-devops-model@1.0.0
15 verbose cwd /home/omar/aws-codecommit-devops-model
16 verbose Linux 4.15.0-99-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "init"
18 verbose node v14.3.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error aws-codecommit-devops-model@1.0.0 init: `npm i --prefix assets/approval-rule-template && npm i --prefix assets/pr-build-events && npm i && ./node_modules/aws-cdk/bin/cdk bootstrap`
22 error Exit status 1
23 error Failed at the aws-codecommit-devops-model@1.0.0 init script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by zxkane** [comment]
Looks like it's caused by `docker` not usable in your env. Recent `aws-cdk` release started to use `docker` image to compile the typescript source of Lambda function.

**Comment by zxkane** [comment]
As a quick workaround, you can check out the commit 4c54465 to use older `aws-cdk` if you don't have `docker` in your env.

**Comment by omar16100** [comment]
Installing Docker solves the issue.
